'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var FactionSchema = new Schema({
  key: String,
  index: String,
  unknown1: String,
  subculture: String,
  category: String,
  screen_name: String,
  screen_adjective: String,
  name_group: String,
  skin: String,
  ui_skin: String,
  is_rebel: String,
  mp_use_republic_early: String,
  mp_use_republic_late: String,
  icons_path_units: String,
  flags_path: String,
  republican_flag_path: String,
  same_gov_type_revolution_flag_path: String,
  primary_colour_r: String,
  primary_colour_g: String,
  primary_colour_b: String,
  alt_primary_colour_r: String,
  alt_primary_colour_g: String,
  alt_primary_colour_b: String,
  secondary_colour_r: String,
  secondary_colour_g: String,
  secondary_colour_b: String,
  alt_secondary_colour_r: String,
  alt_secondary_colour_g: String,
  alt_secondary_colour_b: String,
  uniform_colour_r: String,
  uniform_colour_g: String,
  uniform_colour_b: String,
  alt_uniform_colour_r: String,
  alt_uniform_colour_g: String,
  alt_uniform_colour_b: String,
  military_group: String,
  settler_rebellion_faction: String,
  rebel_colour_r: String,
  rebel_colour_g: String,
  rebel_colour_b: String,
  movie_death_event: String,
  screen_name_when_rebels: String,
  unit_regiment_name_group: String,
  ship_name_group: String,
  attack_desc: String,
  defend_desc: String,
  clan_summary_name: String,
  pre_battle_speech_parameter: String,
  can_be_regionless: String,
  card_colour_r: String,
  card_colour_g: String,
  card_colour_b: String,
  diplomacy_culture: String,
  senator_total: String,
  unknown2: String

});

module.exports = mongoose.model('factions', FactionSchema);