'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var LandUnitSchema = new Schema({
  accuracy: Number,
  ammo: Number,
  armour: String,
  campaign_action_points: String,
  category: String,
  charge_bonus: Number,
  class: String,
  dismounted_charge_bonus: Number,
  dismounted_melee_attack: Number,
  dismounted_melee_defence: Number,
  unknown11: String,
  key: String,
  man_animation: String,
  man_entity: String,
  melee_attack: Number,
  melee_defence: Number,
  morale: Number,
  bonus_hit_points: Number,
  mount: String,
  num_animals: Number,
  animal: String,
  num_mounts: Number,
  primary_melee_weapon: String,
  primary_missile_weapon: String,
  rank_depth: String,
  shield: String,
  short_description_text: String,
  spacing: String,
  strengths_weaknesses_text: String,
  supports_first_person: String,
  training_level: String,
  num_guns: String,
  officers: String,
  articulated_record: String,
  engine: String,
  is_male: String,
  visibility_spotting_range_min: Number,
  visibility_spotting_range_max: Number,
  ability_global_recharge: String,
  attribute_group: String,
  spot_dist_tree: String,
  spot_dist_scrub: String,
  chariot: String,
  num_chariots: Number,
  reload: Number,
  loose_spacing: String,
  spotting_and_hiding: String,
  selection_vo: String,
  selected_vo_secondary: String,
  selected_vo_tertiary: String,
  hiding_scalar: String
});

module.exports = mongoose.model('land_units', LandUnitSchema);